Python 2.7:
  script:
  - py_version=2.7
  - EXTRA_INSTALL=numpy
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - gfortran
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3:
  script:
  - py_version=3
  - EXTRA_INSTALL=numpy
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3
  - gfortran
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Documentation:
  script:
  - EXTRA_INSTALL="numpy"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-docs.sh
  - ". ./build-docs.sh"
  tags:
  - python3
  only:
  - master

Pylint:
  script:
  - export PY_EXE=python3
  - EXTRA_INSTALL="numpy"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-pylint.sh
  - ". ./prepare-and-run-pylint.sh dagrt test/test_*.py"
  tags:
  - python3
  except:
  - tags

Flake8:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
  - ". ./prepare-and-run-flake8.sh dagrt test"
  tags:
  - python3
  except:
  - tags
